apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: uav-recon-hpa-dev
  namespace: uav-recon
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: uav-recon-dev
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 65
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 6Gi
