apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: uav-recon-hpa-dev
  namespace: uav-recon
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: uav-recon-dev
  targetCPUUtilizationPercentage: 60