version: '3.4'

x-var: &APP_NAME
         ${CONTAINER_NAME:-uav-recon}

services:

  database:
    image: postgres:12.2-alpine
    container_name: pg-docker
    environment:
      POSTGRES_PASSWORD: "docker"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "uav_recon"
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
  server:
    image: *APP_NAME
    container_name: *APP_NAME
    build: .
    ports:
      - ${EXTERNAL_PORT:-80}:${DOCKER_PORT:-8080}
    volumes:
      - ${HOME}/uav-recon:/uav-recon
    depends_on:
      - database

volumes:
  dbdata: