version: '3.4'

x-var: &APP_NAME
         ${CONTAINER_NAME:-uav-recon}

services:

  database:
    image: postgres
    container_name: pg-docker
    environment:
      - POSTGRES_PASSWORD=docker
    ports:
      - 5432:5432
    volumes:
      - /var/lib/uav-recon/docker/volumes/postgres:/var/lib/postgresql/data
  server:
    image: *APP_NAME
    container_name: *APP_NAME
    build: .
    ports:
      - ${EXTERNAL_PORT:-80}:${DOCKER_PORT:-8080}
    volumes:
      - ${HOME}/uav-recon:/uav-recon
    depends_on:
      - database
