spring:
  profiles:
    active: default
  mail:
    host: smtp.gmail.com
    port: 587
    username: no-reply@omega-r.com
    password: 12345678
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://database:5432/uav_recon
    username: postgres
    password: docker
  jpa:
    show-sql: true
    format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
server:
  port: 8080
  undertow:
    worker-threads: 32
file:
  uploadDir: /var/lib/uav-recon/files

token:
    secret: WV0TzjM5ZM414ivwUPMj
    tokenExpirationTime: 1800
