apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: uav-recon-hpa-prod
  namespace: uav-recon
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: uav-recon-prod
  targetCPUUtilizationPercentage: 60