apiVersion: v1
kind: Namespace
metadata:
  name: uav-recon

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: datarecon-cicd-default
  namespace: uav-recon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: datarecon-cicd
subjects:
- kind: ServiceAccount
  name: datarecon-cicd
  namespace: uav-recon

---
apiVersion: v1
kind: Service
metadata:
  name: uav-recon-svc-prod
  namespace: uav-recon
spec:
  type: LoadBalancer
  loadBalancerIP: 34.94.146.212
  selector:
    app: uav-recon-prod
  ports:
  - port: 80
    targetPort: 8080
