package com.uav_recon.app.api.entities.db

enum class StructureComponentType {
    BRIDGES_AND_AERIAL_STRUCTURE,
    RETAINING_WALLS_AND_CONCENTRATE_TRACKS,
    SUBWAY_STATIONS_AND_AERIAL_STATIONS,
    SUBWAY_TUNNELS_USECTION
}